version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/kenju/goserver

    steps:
      - checkout

      - run:
        command: |
          make lint
          make fmt
          make test
